baseURL: "https://chutommy.github.io/prondru/"
enableInlineShortcodes: true
languageCode: "en-us"
title: "Prondru Project"
theme: "uwe-uwe"
relativeURLs: true

disableKinds:
  - "section"
  - "taxonomy"
  - "term"
  - "RSS"

markup:
  goldmark:
    renderer:
      unsafe: true
    highlight:
      style: igor

params:

  uweuwe:
    metadata:
      author: "Tommy Chu"

    logo:
      display: true
      src: "/assets/img/logo/logo.png"

    favicon:
      display: true
      src: "/assets/img/logo/favicon.png"

    shortDesc:
      display: true
      value: "The documentation of the project PrOndru, the CLI for the Office of Scientific and Technical Information API."

    platformLinks:
      display: true
      displayMode: "as-icons-and-text"

      platforms:
        - name: "author"
          display: true
          iconSrc: "/assets/img/platforms/personal.png"
          target: "https://chutommy.github.io/"
          text: "Author"
          title: "Go to author's website"

        - name: "source"
          display: true
          iconSrc: "/assets/img/platforms/github.png"
          target: "https://github.com/chutommy/observer"
          text: "Source"
          title: "Go to the Observer Github repository"

        - name: "osti"
          display: true
          iconSrc: "/assets/img/platforms/document.png"
          target: "https://www.osti.gov/"
          text: "OSTI"
          title: "Go to the Office of Scientific and Technical Information official website"

    toc:
      display: false

    googleAnalytics:
      active: true
      id: G-GNYV28RSRW

    renderHooks:
      image:
        use: true

      link:
        use: true

      heading:
        use: true

    syntaxHiglighingCustom:
      use: false